name: Sandbox - Build and Deploy

on:
  push:
    branches: sandbox 
#normally you wouldn't be deploying master branch pushes to Sandbox,
#but we're keeping things simple! 😁

#setup enviroment variables using github secrets that will be utilized for setting.xml and pom.xml
env:
  NEXUS_USERNAME: ${{ secrets.NEXUSUSERNAME }}
  NEXUS_PASSWORD: ${{ secrets.NEXUSPASSWORD }}
  PLATFORM_USERNAME: ${{ secrets.PLATFORMUSERNAME }}
  PLATFORM_PASSWORD: ${{ secrets.PLATFORMPASSWORD }}
  ENVIRONMENT: ${{ secrets.ENVIRONMENT}}

jobs:
  BuildAndDeployToDev:
    runs-on: ubuntu-latest
    environment:
      name: Sandbox
    steps:
#first, we need to checkout our mule application's branch code
      - name: Checkout repository
        uses: actions/checkout@v2
#second, cache dependencies, No need to download every time
      - name: cache dependencies
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
#third, build with Maven
      - name: Build with Maven
        run: mvn -B clean package -s .maven/settings.xml
#fourth, upload artifact, to utilize for other repo.(optional)
      - name: upload Artifact
        run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
#fifth, Deploy with Maven
      - name: Deploy
        run: mvn -B deploy -DmuleDeploy -s .maven/settings.xml
